# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  Chromatic:
    # Operating System
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'dependabot[bot]' }}
    # Job steps
    steps:
      #- run: echo "PR created by Dependabot"
      - uses: actions/checkout@v1
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
