name: 🧐 Generate Docker image
on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron:  '12 0 * * *'
jobs:
  build:
    name: 👩🏼‍🏭 Build Docker Image 👩🏼‍🏭
    runs-on: ubuntu-latest
    services:
      kaoto:
        image: kaotoio/backend:main
        ports:
        # will assign a random free host port
          - 8081/tcp
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
        if: ${{env.username != ''}}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kaotoio/frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          username: ${{ secrets.DOCKER_USERNAME }}
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: Build to test
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false
      - name: Run built image
        if: ${{ github.event_name == 'pull_request' }}
        run: docker run -d --rm -e KAOTO_API="http://localhost:8081" --name kaoto-ui kaotoio/frontend:pr-${{ github.event.pull_request.number }}
      - name: Check health
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: kaoto-ui
          wait-time: 50
          require-status: running
          require-healthy: true
      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

